### ISSUE TITLE
Ch-05 Сетка, перемещение, зум

### ISSUE THREAD

**Issue by nfpirus** [nfpirus/canvasHouse#11]
Реализовать на бекграунде сетку,
а так же поддерживаемый функционал:
-  перемещение по сцене через mouseMove 
-  зум через mouseScroll

**Comment by nihlete** [comment]
Может перемещение по сцене через mouseDrag сделать?

**Comment by nfpirus** [comment]
а это что за эвент mouseDrag ?
под  mouseMove я понимаю что срабатывает после mouseDown и срабатывает перемещение до mouseUp
Или всмысе есть такой функционал в paperJs?

**Comment by nihlete** [comment]
Есть

**Comment by nfpirus** [comment]
> Можно жестко задать pivot для любого PathItem и группы позиция объекта будет совпадать с pivot(наверно из майи знакомо понятие). С другой стороны смысла в тексте не было.
