### ISSUE TITLE
CH-06 Пользовательское изображение на фоне

### ISSUE THREAD

**Issue by nihlete** [nfpirus/canvasHouse#12]
Пользовательское изображение на фоне с возможностью его масштабирования/замены

**Comment by nfpirus** [comment]
"Для реализации функционала загрузки файла стандартно в html используется 
<input type="file" атрибуты> При этом поле в различных браузерах выглядит по разному http://htmlbook.ru/samhtml5/formy/zagruzka-failov. Но что еще хуже, загрузку напрямую в DOM разметку реализовать вроде как нельзя, нужно предварительно загрузить на сервер (как показано в примере). Атрибуты не позволяют восстановить полный путь до файла и даже если бы это было возможно, то наверняка параметры безопасности браузеров не допустят работу с файлами на стороне клиента."

**Comment by nfpirus** [comment]
пусть у тебя на странице будет img помести его на канвас и работай над функционалом,
Функционал загрузки и помещение картинки в этот img будет отдельной задачей

**Comment by nfpirus** [comment]
> • иконка для загрузки/удаления подложки на текущем уровне. Если подложка уже загружена отображать кнопки : удалить/скрыть/отобразить, если подложка не загружена иконка “загрузить”
> 
> • После загрузки картинки должна быть возможность пропорционального масштабирования этой подложки в любой момент, когда пожелает пользователь, потянув за уголок объекта подложки.  
> Подложка должна иметь свойство “скрытия/отображения”.
