### ISSUE TITLE
CH-7 Создать элемент управления 

### ISSUE THREAD

**Issue by nihlete** [nfpirus/canvasHouse#14]
Желтые квадратики.
![default](https://cloud.githubusercontent.com/assets/9762164/14088654/64bbbd5c-f539-11e5-9243-e1c74c18bf42.PNG)

``` Typescript
class ShapeInnerWall implements IShape {
    public type: number = 2;
    public coord: ICoordinates;
    public childrens: Array<IShape>;
    public valid: boolean;
    public renderObject: paper.Group;

    constructor(coordinates: ICoordinates) {
        this.coord = coordinates;
    }
}
```

Сами элементы будут добавляться в`childrens: Array<IShape>;` (там где необходимо) в качестве первых двух детей. Первым делом организую события onMouseDrag.

Насчет этого хочу спросить, в каком месте лучше устанавливать их внутрь класса?  В конструкторе класса или в RenderApi? Во втором случае меньше зависимостей, а в первом вроде -- полное определение класса

**Comment by nfpirus** [comment]
- не правильно прочитал! RenderApi (в рендерApi необходимо добавить метод который позволяет устнавливать событие)
- по поводу класть в childrens: Array<IShape>; интересный вопрос, но пока можно сделать и так
  в общем лучше в ShapeInnerWall добавить отдельные свойства и методы для работы с маркерами (Желтые квадратики)

**Comment by nfpirus** [comment]
пример использования childrens:

> ```
>               children: [
>                     {
>                         type: 5,
>                         coordinates: [
>                             { x: 0, y: 2100 },
>                             { x: 0, y: 2300 }
>                         ], 
>                     },
>                     {
>                         type: 6,
>                         coordinates: [
>                             { x: 0, y: 2400 },
>                             { x: 0, y: 2600 }
>                         ], 
>                     }
>                 ]
> ```

**Comment by nihlete** [comment]
> лучше в ShapeInnerWall добавить отдельные свойства и методы для работы с маркерами

Получается обработчики событий в RenderAPI, внутри классов добавить полей под обработчики?

> `children: [ { type: 5, coordinates: [ { x: 0, y: 2100 }, { x: 0, y: 2300 } ], }, { type: 6, coordinates: [ { x: 0, y: 2400 }, { x: 0, y: 2600 } ], } ]`

Пример для того, что бы показать что внутри children массив и заполнять его можно при помощи объектов в описании js?

**Comment by nfpirus** [comment]
Да)

Да, пример взял из описания хотелось бы сохранить функциональную чистоту чюлдренов ( они нужны для хранения шейпов типа окно, дверь, ...)

**Comment by nfpirus** [comment]
механизм "рисования" стен отдельным таском будем реализовывать?
