### ISSUE TITLE
CH-13 Алгоритм замкнутости

### ISSUE THREAD

**Issue by nfpirus** [nfpirus/canvasHouse#24]
Если в процессе рисования стен получилось замкнутая фигура необходимо произвести расчет площади

> стены должны уметь “приклеиваться” краями к уже нанесенным стенам, а внутренние объекты (двери/окна/проемы) должны уметь приклеиваться к плоскостям стены при близком расположении

**Comment by nfpirus** [comment]
для начала бы просто понять что фигура замкнута, при этом рисовать стены можно в несколько этапов

**Comment by nihlete** [comment]
Наверно лучше всего строить модель пути `paper.Path`. Встроенного метода, который позволяет проверить на замкнутость нет, но можно проверить по сегментам.

``` javascript
var myPath = new Path();
myPath.strokeColor = 'black';
myPath.add(new Point(50, 75));
myPath.add(new Point(100, 25));
myPath.add(new Point(150, 75));
myPath.add(new Point(50, 75));
console.log(myPath.isClosed()); //false
myPath.closed = true;
console.log(myPath.isClosed()); //true
console.log(myPath.firstSegment.point.equals(myPath.lastSegment.point)); //true
```

**Comment by nfpirus** [comment]
замкнуться может по нескольким отдельным стен в процессе редактирования , -> алгоритм замкнутости должен быть свой проанализировать все шейпы с типом внешняя стены
