### ISSUE TITLE
CH-16 Проблема с событиями

### ISSUE THREAD

**Issue by nihlete** [nfpirus/canvasHouse#29]
При следующей последовательности действий происходит сброс событий onMouseDown
1. Клик Стена-Добавить стену.
2. Нарисовать 1(количество не принципиально) стену.
3. Клик Курсор.
4. Клик Стена-Добавить стену.
5. Нарисовать стену.
6. Клик Курсор, события не действуют.

При этом случайным образом происходит самопроизвольное изменение масштаба на максимально удаленное.

**Comment by nfpirus** [comment]
кстати не замечал что периодически при бездействии canvas становится белым ?
как решение вызывать тайм аутом редроу у paper

**Comment by nihlete** [comment]
можно еще перерисовку onFrame сделать http://paperjs.org/reference/view/#onframe

**Comment by nfpirus** [comment]
onFrame не помогает
