### ISSUE TITLE
CH-18 Работа с объектами

### ISSUE THREAD

**Issue by nfpirus** [nfpirus/canvasHouse#32]
> Каждый элемент после установки должен так же иметь возможность изменения как по позиции так и по параметрам. После установки элемента необходимо выводить его параметры для контроля и изменения. Все элементы имеют один параметр - длину в мм

**Comment by nihlete** [comment]
Частично занят в рамках моего таска

**Comment by nfpirus** [comment]
давай тогда разнесем, какой именно фрагмент ?

**Comment by nihlete** [comment]
Занимаюсь созданием склееной цепочки стен, потом соответственно отдельно стены сделаю, фиксированные проемы тоже разрабатываю.

Вторую задачу не решаю пока.
