### ISSUE TITLE
CH-01 Отрисовка объектов

### ISSUE THREAD

**Issue by nfpirus** [nfpirus/canvasHouse#4]
Реализовать RenderApi. Необходим предварительный вариант визуализации объектов:
1.  Внешняя несущая стена
2.  Внутренняя несущая стена
3.  Колонна
4.  Перегородка
5.  Окно
6.  Дверь
7.  Проём
Детальную реализацию будем делать в конце.

**Comment by nihlete** [comment]
Что такое проем? ~~Дырка~~ Отверстие в стене в размер дверного проема?

**Comment by nfpirus** [comment]
Да дверной проем без двери ток =)
В аналоге вроде можно глянуть
